services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: rankradar
      POSTGRES_PASSWORD: rankradar
      POSTGRES_DB: rankradar
    ports:
      - "5432:5432"
    volumes:
      - rankradar_pg:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - rankradar_mongo:/data/db
volumes:
  rankradar_pg:
  rankradar_mongo:
